services:
  main:
    image: "s3proxy/main"
    environment:
      - "PORT=8080"
      - "SSO_URL_INTERNAL=http://localhost:8081/"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - minio

  sso:
    profiles:
      - donotstart
