services:
  main:
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
      - "SSO_URL_INTERNAL=http://sso:8082/"
    depends_on:
      - redis
      - minio
      - sso

  # used for dev ONLY; mocks SSO auth
  sso:
    build:
      context: .
      dockerfile: "docker/Dockerfile.sso"
    networks:
      - default
      - inside
    environment:
      - PORT=8082
    command: "poetry run python -m sso_server"
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
