version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2 # /PS-IGNORE
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            cp .env.ci .env
            make build
            make up-detached
      - run:
          name: Lint & Format
          command: |
            make format
            make flake8
            make mypy
            make check-fixme
      - run:
          name: Test
          command: |
            make test
      - codecov/upload
      - run: make down
