version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2 # /PS-IGNORE
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: cp .env.ci .env
      - run: make build
      - run: make up-detached
      - run: make format
      - run: make flake8
      - run: make mypy
      - run: make test
      - codecov/upload
      - run: make down
