version: 2
jobs:
    build:
        machine:
            image: ubuntu-2004:202101-01
        steps:
            - checkout
            - run:
                name: Copy env file
                command: cp .env.ci .env
            - run:
                name: build containers
                command: make build
            - run:
                name: run black (code formatting check)
                command: make black
            - run:
                name: run flake8 (coding standards compliance test)
                command: make flake8
