name: Run tests

on:
  push:
    branches:
      - "main" # committing directly to main
      - "master"
  pull_request:
    branches:
      - "main" # merging into main
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # custom docker builder to enable next step
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache layers locally
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        # this caches the docker layers
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: "docker/Dockerfile.dev"
          cache-from: type=gha,src=/tmp/.buildx-cache
          cache-to: type=gha,dest=/tmp/.buildx-cache
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: true
      - name: Setup
        run: |
            cp .env.ci .env
            make setup-ci
      - name: Lint & Format
        run: make lint-ci
      - name: Test
        run: make test-ci
        # codecov ?
