name: Run tests

on:
  push:
    branches:
      - "main" # committing directly to main
      - "master"
  pull_request:
    branches:
      - "main" # merging into main
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        # custom docker builder to enable next step
      - run: cp .env.ci .env
      - uses: docker/setup-buildx-action@v3
        # this caches the docker layers
      - name: Build & cache main docker image
        uses: docker/bake-action@v5.0.0
        with:
          files: |
            docker-compose.yml
            docker-compose.test.yml
          push: false
          load: true
          set: |
            main.cache-from=type=gha
            main.cache-to=type=gha
            main.tags=s3proxy/main
      - name: Run containers
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker compose -f docker-compose.yml -f docker-compose.test.yml up -d
      - name: Lint & Format
        run: make lint-ci
      - name: Test
        run: make test-ci
        # codecov ?
