name: Run tests

on:
  push:
    branches:
      - "main" # committing directly to main
      - "master"
  pull_request:
    branches:
      - "main" # merging into main
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: "docker/Dockerfile.dev"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup
        run: |
            cp .env.ci .env
            make setup-ci
      - name: Lint & Format
        run: make lint-ci
      - name: Test
        run: make test-ci
        # codecov ?
