name: Run tests

on:
  push:
    branches:
      - "main" # committing directly to main
      - "master"
  pull_request:
    branches:
      - "main" # merging into main
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # custom docker builder to enable next step
      - uses: docker/setup-buildx-action@v2
        # this caches the docker layers
      - name: Build & cache main docker image
        uses: docker/bake-action@v2.0.0
        with:
          push: false
          load: true
          set: |
            web.cache-from=type=gha
            web.cache-to=type=gha
            web.tags=s3proxy/main
      - name: Setup
        run: |
            cp .env.ci .env
            make setup-ci
      - name: Lint & Format
        run: make lint-ci
      - name: Test
        run: make test-ci
        # codecov ?
